auto_scale_lr = dict(base_batch_size=16, enable=False)
backend_args = None
custom_imports = dict(
    imports=['cnsn_models.resnet_cnsn'],
    allow_failed_imports=False
)
data_root = 'E:\\KaryoNet_data\\dj_prepare\\'
dataset_type = 'CocoDataset'
default_hooks = dict(
    checkpoint=dict(
        by_epoch=True,
        interval=5,
        max_keep_ckpts=10,
        save_last=True,
        type='CheckpointHook'),
    logger=dict(interval=50, type='LoggerHook'),
    param_scheduler=dict(type='ParamSchedulerHook'),
    sampler_seed=dict(type='DistSamplerSeedHook'),
    timer=dict(type='IterTimerHook'))
default_scope = 'mmdet'
dynamic_intervals = [
    (
        365001,
        368750,
    ),
]
embed_multi = dict(decay_mult=0.0, lr_mult=1.0)
env_cfg = dict(
    cudnn_benchmark=False,
    dist_cfg=dict(backend='nccl'),
    mp_cfg=dict(mp_start_method='fork', opencv_num_threads=0))
image_size = (
    1024,
    1024,
)
interval = 5000
launcher = 'none'
load_from = None
log_level = 'INFO'
log_processor = dict(by_epoch=False, type='LogProcessor', window_size=50)
max_iters = 368750
metainfo = dict(
    classes=(
        'chromosome_01',
        'chromosome_02',
        'chromosome_03',
        'chromosome_04',
        'chromosome_05',
        'chromosome_06',
        'chromosome_07',
        'chromosome_08',
        'chromosome_09',
        'chromosome_10',
        'chromosome_11',
        'chromosome_12',
        'chromosome_13',
        'chromosome_14',
        'chromosome_15',
        'chromosome_16',
        'chromosome_17',
        'chromosome_18',
        'chromosome_19',
        'chromosome_20',
        'chromosome_21',
        'chromosome_22',
        'chromosome_23',
        'chromosome_24',
    ),
    palette=[
        (
            31,
            119,
            180,
        ),
        (
            174,
            199,
            232,
        ),
        (
            255,
            127,
            14,
        ),
        (
            255,
            187,
            120,
        ),
        (
            44,
            160,
            44,
        ),
        (
            152,
            223,
            138,
        ),
        (
            214,
            39,
            40,
        ),
        (
            255,
            152,
            150,
        ),
        (
            148,
            103,
            189,
        ),
        (
            197,
            176,
            213,
        ),
        (
            140,
            86,
            75,
        ),
        (
            196,
            156,
            148,
        ),
        (
            227,
            119,
            194,
        ),
        (
            247,
            182,
            210,
        ),
        (
            127,
            127,
            127,
        ),
        (
            199,
            199,
            199,
        ),
        (
            188,
            189,
            34,
        ),
        (
            219,
            219,
            141,
        ),
        (
            23,
            190,
            207,
        ),
        (
            158,
            218,
            229,
        ),
        (
            158,
            218,
            229,
        ),
        (
            158,
            218,
            229,
        ),
        (
            158,
            218,
            229,
        ),
        (
            158,
            218,
            229,
        ),
    ])
model = dict(
    backbone=dict(
        active_num=1,
        beta=1,
        block_idxs='1_2_3_4',
        cn_pos='post',
        cnsn_type='cnsn',
        crop='style',
        groups=1,
        init_cfg=dict(
            checkpoint=
            'E:\\KaryoNet-main\\6k_finetune\\resized_weights\\epoch_50.pth'
        ),
        layers=[
            3,
            4,
            6,
            3,
        ],
        norm_layer=None,
        num_classes=1000,
        pos='residual',
        replace_stride_with_dilation=None,
        type='ResNet_CNSN',
        width_per_group=64,
        zero_init_residual=False),
    data_preprocessor=dict(
        batch_augments=[
            dict(
                img_pad_value=255,
                mask_pad_value=0,
                pad_mask=True,
                pad_seg=False,
                size=(
                    1024,
                    1024,
                ),
                type='BatchFixedSizePad'),
        ],
        bgr_to_rgb=True,
        mask_pad_value=0,
        mean=[
            241.72,
            241.72,
            241.72,
        ],
        pad_mask=True,
        pad_seg=False,
        pad_size_divisor=32,
        seg_pad_value=255,
        std=[
            21.32,
            21.32,
            21.32,
        ],
        type='DetDataPreprocessor'),
    init_cfg=None,
    panoptic_fusion_head=dict(
        init_cfg=None,
        loss_panoptic=None,
        num_stuff_classes=0,
        num_things_classes=24,
        type='MaskFormerFusionHead'),
    panoptic_head=dict(
        enforce_decoder_input_project=False,
        feat_channels=256,
        in_channels=[
            256,
            512,
            1024,
            2048,
        ],
        loss_cls=dict(
            class_weight=[
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                1.0,
                0.1,
            ],
            loss_weight=2.0,
            reduction='mean',
            type='CrossEntropyLoss',
            use_sigmoid=False),
        loss_dice=dict(
            activate=True,
            eps=1.0,
            loss_weight=5.0,
            naive_dice=True,
            reduction='mean',
            type='DiceLoss',
            use_sigmoid=True),
        loss_mask=dict(
            loss_weight=5.0,
            reduction='mean',
            type='CrossEntropyLoss',
            use_sigmoid=True),
        num_queries=100,
        num_stuff_classes=0,
        num_things_classes=24,
        num_transformer_feat_level=3,
        out_channels=256,
        pixel_decoder=dict(
            act_cfg=dict(type='ReLU'),
            encoder=dict(
                layer_cfg=dict(
                    ffn_cfg=dict(
                        act_cfg=dict(inplace=True, type='ReLU'),
                        embed_dims=256,
                        feedforward_channels=1024,
                        ffn_drop=0.0,
                        num_fcs=2),
                    self_attn_cfg=dict(
                        batch_first=True,
                        dropout=0.0,
                        embed_dims=256,
                        num_heads=8,
                        num_levels=3,
                        num_points=4)),
                num_layers=6),
            norm_cfg=dict(num_groups=32, type='GN'),
            num_outs=3,
            positional_encoding=dict(normalize=True, num_feats=128),
            type='MSDeformAttnPixelDecoder'),
        positional_encoding=dict(normalize=True, num_feats=128),
        strides=[
            4,
            8,
            16,
            32,
        ],
        transformer_decoder=dict(
            init_cfg=None,
            layer_cfg=dict(
                cross_attn_cfg=dict(
                    batch_first=True, dropout=0.0, embed_dims=256,
                    num_heads=8),
                ffn_cfg=dict(
                    act_cfg=dict(inplace=True, type='ReLU'),
                    embed_dims=256,
                    feedforward_channels=2048,
                    ffn_drop=0.0,
                    num_fcs=2),
                self_attn_cfg=dict(
                    batch_first=True, dropout=0.0, embed_dims=256,
                    num_heads=8)),
            num_layers=9,
            return_intermediate=True),
        type='Mask2FormerHead'),
    test_cfg=dict(
        filter_low_score=True,
        instance_on=True,
        iou_thr=0.8,
        max_per_image=100,
        panoptic_on=False,
        semantic_on=False),
    train_cfg=dict(
        assigner=dict(
            match_costs=[
                dict(type='ClassificationCost', weight=2.0),
                dict(
                    type='CrossEntropyLossCost', use_sigmoid=True, weight=5.0),
                dict(eps=1.0, pred_act=True, type='DiceCost', weight=5.0),
            ],
            type='HungarianAssigner'),
        importance_sample_ratio=0.75,
        num_points=12544,
        oversample_ratio=3.0,
        sampler=dict(type='MaskPseudoSampler')),
    type='Mask2Former')
num_classes = 24
num_stuff_classes = 0
num_things_classes = 24
optim_wrapper = dict(
    clip_grad=dict(max_norm=0.01, norm_type=2),
    optimizer=dict(
        betas=(
            0.9,
            0.999,
        ),
        eps=1e-08,
        lr=0.0001,
        type='AdamW',
        weight_decay=0.05),
    paramwise_cfg=dict(
        custom_keys=dict(
            backbone=dict(decay_mult=1.0, lr_mult=0.1),
            level_embed=dict(decay_mult=0.0, lr_mult=1.0),
            query_embed=dict(decay_mult=0.0, lr_mult=1.0),
            query_feat=dict(decay_mult=0.0, lr_mult=1.0)),
        norm_decay_mult=0.0),
    type='OptimWrapper')
param_scheduler = [
    dict(begin=0, by_epoch=False, end=500, start_factor=0.05, type='LinearLR'),
    dict(
        begin=0,
        by_epoch=True,
        end=50,
        gamma=0.1,
        milestones=[
            30,
            40,
        ],
        type='MultiStepLR'),
]
resume = True
test_cfg = dict(type='TestLoop')
test_dataloader = dict(
    batch_size=1,
    dataset=dict(
        ann_file='annotations/val_500.json',
        backend_args=None,
        data_prefix=dict(img='val_500/', seg='annotations/panoptic_val2017/'),
        data_root=
        'E:\\KaryoNet_data\\dj_prepare',
        #这个.pt训练的时候category_id (6,7), (14,15) 写反了，所以test 的时候
        metainfo=dict(
            classes=(
                'chromosome_01',
                'chromosome_02',
                'chromosome_03',
                'chromosome_04',
                'chromosome_05',
                'chromosome_07', #reverse
                'chromosome_06', #reverse
                'chromosome_08',
                'chromosome_09',
                'chromosome_10',
                'chromosome_11',
                'chromosome_12',
                'chromosome_13',
                'chromosome_15', #reverse
                'chromosome_14', #reverse
                'chromosome_16',
                'chromosome_17',
                'chromosome_18',
                'chromosome_19',
                'chromosome_20',
                'chromosome_21',
                'chromosome_22',
                'chromosome_23',
                'chromosome_24',
            ),
            palette=[
                (
                    31,
                    119,
                    180,
                ),
                (
                    174,
                    199,
                    232,
                ),
                (
                    255,
                    127,
                    14,
                ),
                (
                    255,
                    187,
                    120,
                ),
                (
                    44,
                    160,
                    44,
                ),
                (
                    152,
                    223,
                    138,
                ),
                (
                    214,
                    39,
                    40,
                ),
                (
                    255,
                    152,
                    150,
                ),
                (
                    148,
                    103,
                    189,
                ),
                (
                    197,
                    176,
                    213,
                ),
                (
                    140,
                    86,
                    75,
                ),
                (
                    196,
                    156,
                    148,
                ),
                (
                    227,
                    119,
                    194,
                ),
                (
                    247,
                    182,
                    210,
                ),
                (
                    127,
                    127,
                    127,
                ),
                (
                    199,
                    199,
                    199,
                ),
                (
                    188,
                    189,
                    34,
                ),
                (
                    219,
                    219,
                    141,
                ),
                (
                    23,
                    190,
                    207,
                ),
                (
                    158,
                    218,
                    229,
                ),
                (
                    158,
                    218,
                    229,
                ),
                (
                    158,
                    218,
                    229,
                ),
                (
                    158,
                    218,
                    229,
                ),
                (
                    158,
                    218,
                    229,
                ),
            ]),
        pipeline=[
            dict(backend_args=None, to_float32=True, type='LoadImageFromFile'),
            dict(keep_ratio=True, scale=(
                1024,
                1024,
            ), type='Resize'),
            dict(type='LoadAnnotations', with_bbox=True, with_mask=True),
            dict(
                meta_keys=(
                    'img_id',
                    'img_path',
                    'ori_shape',
                    'img_shape',
                    'scale_factor',
                ),
                type='PackDetInputs'),
        ],
        test_mode=True,
        type='CocoDataset'),
    drop_last=True,
    num_workers=2,
    persistent_workers=True,
    sampler=dict(shuffle=False, type='DefaultSampler'))
test_evaluator = dict(
    ann_file=
    'E:\\KaryoNet_data\\dj_prepare\\annotations\\val_500.json',
    backend_args=None,
    format_only=False,
    metric=[
        'bbox',
        'segm',
    ],
    type='CocoMetric')
test_pipeline = [
    dict(backend_args=None, to_float32=True, type='LoadImageFromFile'),
    dict(keep_ratio=True, scale=(
        1024,
        1024,
    ), type='Resize'),
    dict(type='LoadAnnotations', with_bbox=True, with_mask=True),
    dict(
        meta_keys=(
            'img_id',
            'img_path',
            'ori_shape',
            'img_shape',
            'scale_factor',
        ),
        type='PackDetInputs'),
]
train_cfg = dict(max_epochs=50, type='EpochBasedTrainLoop', val_interval=5)
train_dataloader = dict(
    batch_size=4,
    dataset=dict(
        ann_file='annotations/train_v2_6000.json',
        backend_args=None,
        data_prefix=dict(
            img='train_v2_6000/', seg='annotations/panoptic_train2017/'),
        data_root='E:\\KaryoNet_data\\dj_prepare',
        filter_cfg=dict(filter_empty_gt=True, min_size=32),
        metainfo=dict(
            classes=(
                'chromosome_01',
                'chromosome_02',
                'chromosome_03',
                'chromosome_04',
                'chromosome_05',
                'chromosome_06',
                'chromosome_07',
                'chromosome_08',
                'chromosome_09',
                'chromosome_10',
                'chromosome_11',
                'chromosome_12',
                'chromosome_13',
                'chromosome_14',
                'chromosome_15',
                'chromosome_16',
                'chromosome_17',
                'chromosome_18',
                'chromosome_19',
                'chromosome_20',
                'chromosome_21',
                'chromosome_22',
                'chromosome_23',
                'chromosome_24',
            ),
            palette=[
                (
                    31,
                    119,
                    180,
                ),
                (
                    174,
                    199,
                    232,
                ),
                (
                    255,
                    127,
                    14,
                ),
                (
                    255,
                    187,
                    120,
                ),
                (
                    44,
                    160,
                    44,
                ),
                (
                    152,
                    223,
                    138,
                ),
                (
                    214,
                    39,
                    40,
                ),
                (
                    255,
                    152,
                    150,
                ),
                (
                    148,
                    103,
                    189,
                ),
                (
                    197,
                    176,
                    213,
                ),
                (
                    140,
                    86,
                    75,
                ),
                (
                    196,
                    156,
                    148,
                ),
                (
                    227,
                    119,
                    194,
                ),
                (
                    247,
                    182,
                    210,
                ),
                (
                    127,
                    127,
                    127,
                ),
                (
                    199,
                    199,
                    199,
                ),
                (
                    188,
                    189,
                    34,
                ),
                (
                    219,
                    219,
                    141,
                ),
                (
                    23,
                    190,
                    207,
                ),
                (
                    158,
                    218,
                    229,
                ),
                (
                    158,
                    218,
                    229,
                ),
                (
                    158,
                    218,
                    229,
                ),
                (
                    158,
                    218,
                    229,
                ),
                (
                    158,
                    218,
                    229,
                ),
            ]),
        pipeline=[
            dict(backend_args=None, to_float32=True, type='LoadImageFromFile'),
            dict(type='LoadAnnotations', with_bbox=True, with_mask=True),
            dict(prob=0.5, type='RandomFlip'),
            dict(type='PackDetInputs'),
        ],
        type='CocoDataset'),
    drop_last=False,
    num_workers=2,
    persistent_workers=True,
    sampler=dict(shuffle=True, type='DefaultSampler'))
val_cfg = dict(type='ValLoop')
val_dataloader = dict(
    batch_size=2,
    dataset=dict(
        ann_file='annotations/val_500.json',
        backend_args=None,
        data_prefix=dict(img='val_500/', seg='annotations/panoptic_val2017/'),
        data_root='E:\\KaryoNet_data\\dj_prepare',
        metainfo=dict(
            classes=(
                'chromosome_01',
                'chromosome_02',
                'chromosome_03',
                'chromosome_04',
                'chromosome_05',
                'chromosome_06',
                'chromosome_07',
                'chromosome_08',
                'chromosome_09',
                'chromosome_10',
                'chromosome_11',
                'chromosome_12',
                'chromosome_13',
                'chromosome_14',
                'chromosome_15',
                'chromosome_16',
                'chromosome_17',
                'chromosome_18',
                'chromosome_19',
                'chromosome_20',
                'chromosome_21',
                'chromosome_22',
                'chromosome_23',
                'chromosome_24',
            ),
            palette=[
                (
                    31,
                    119,
                    180,
                ),
                (
                    174,
                    199,
                    232,
                ),
                (
                    255,
                    127,
                    14,
                ),
                (
                    255,
                    187,
                    120,
                ),
                (
                    44,
                    160,
                    44,
                ),
                (
                    152,
                    223,
                    138,
                ),
                (
                    214,
                    39,
                    40,
                ),
                (
                    255,
                    152,
                    150,
                ),
                (
                    148,
                    103,
                    189,
                ),
                (
                    197,
                    176,
                    213,
                ),
                (
                    140,
                    86,
                    75,
                ),
                (
                    196,
                    156,
                    148,
                ),
                (
                    227,
                    119,
                    194,
                ),
                (
                    247,
                    182,
                    210,
                ),
                (
                    127,
                    127,
                    127,
                ),
                (
                    199,
                    199,
                    199,
                ),
                (
                    188,
                    189,
                    34,
                ),
                (
                    219,
                    219,
                    141,
                ),
                (
                    23,
                    190,
                    207,
                ),
                (
                    158,
                    218,
                    229,
                ),
                (
                    158,
                    218,
                    229,
                ),
                (
                    158,
                    218,
                    229,
                ),
                (
                    158,
                    218,
                    229,
                ),
                (
                    158,
                    218,
                    229,
                ),
            ]),
        pipeline=[
            dict(backend_args=None, to_float32=True, type='LoadImageFromFile'),
            dict(keep_ratio=True, scale=(
                1024,
                1024,
            ), type='Resize'),
            dict(type='LoadAnnotations', with_bbox=True, with_mask=True),
            dict(
                meta_keys=(
                    'img_id',
                    'img_path',
                    'ori_shape',
                    'img_shape',
                    'scale_factor',
                ),
                type='PackDetInputs'),
        ],
        test_mode=True,
        type='CocoDataset'),
    drop_last=True,
    num_workers=2,
    persistent_workers=True,
    sampler=dict(shuffle=False, type='DefaultSampler'))
val_evaluator = dict(
    ann_file=
    'E:\\KaryoNet_data\\dj_prepare\\annotations\\val_500.json',
    backend_args=None,
    format_only=False,
    metric=[
        'bbox',
        'segm',
    ],
    type='CocoMetric')
visualizer = dict(
    name='visualizer',
    type='DetLocalVisualizer',
    vis_backends=[
        dict(type='LocalVisBackend'),
    ])
work_dir = 'E:\\KaryoNet_data\\dj_prepare'  