"""
Training (optimisation) worker for the karyotype correction agent.

Loads self-play data files written by karyotype_self_play.py, trains the
KaryotypeModel on (state, policy, value) triples, and periodically saves
the updated model as the next-generation candidate for evaluation.

Mirrors the design of worker/optimize.py.
"""

import os
from collections import deque
from concurrent.futures import ProcessPoolExecutor
from datetime import datetime
from glob import glob
from logging import getLogger
from random import shuffle
from time import sleep

import numpy as np

from chess_zero.agent.model_karyotype import KaryotypeModel
from chess_zero.config import Config

logger = getLogger(__name__)


def start(config: Config):
    return KaryotypeOptimizeWorker(config).start()


class KaryotypeOptimizeWorker:
    """
    Trains the KaryotypeModel using data generated by KaryotypeSelfPlayWorker.

    Attributes
    ----------
    config : Config
    model : KaryotypeModel
    dataset : tuple[deque, deque, deque]
        (states, policies, values) dequeues.
    executor : ProcessPoolExecutor
        Pool for parallel data loading.
    """

    def __init__(self, config: Config):
        self.config = config
        self.model = None
        self.dataset = deque(), deque(), deque()
        self.executor = ProcessPoolExecutor(
            max_workers=config.trainer.cleaning_processes)

    def start(self):
        self.model = self._load_model()
        self._train()

    # ── Training loop ─────────────────────────────────────────────────────────

    def _train(self):
        self._compile_model()
        rc = self.config.resource
        data_files = deque(self._get_data_filenames(rc))
        shuffle(data_files)
        total_steps = self.config.trainer.start_total_steps

        while True:
            self._fill_queue(data_files)
            if len(self.dataset[0]) < self.config.trainer.min_data_size_to_learn:
                logger.info(
                    f"Not enough data yet "
                    f"({len(self.dataset[0])} < "
                    f"{self.config.trainer.min_data_size_to_learn}). "
                    f"Waiting 60 s …")
                sleep(60)
                data_files = deque(self._get_data_filenames(rc))
                continue

            steps = self._train_epoch(self.config.trainer.epoch_to_checkpoint)
            total_steps += steps
            self._save_next_generation_model()

            # Trim dataset
            a, b, c = self.dataset
            while len(a) > self.config.trainer.dataset_size // 2:
                a.popleft()
                b.popleft()
                c.popleft()

            # Refresh file list
            data_files = deque(self._get_data_filenames(rc))
            shuffle(data_files)

    def _train_epoch(self, epochs: int) -> int:
        """
        Run ``epochs`` Keras fit epochs on the current dataset.

        Returns
        -------
        int
            Approximate number of gradient steps.
        """
        tc = self.config.trainer
        state_ary, policy_ary, value_ary = self._collect_data()
        self.model.model.fit(
            state_ary,
            [policy_ary, value_ary],
            batch_size=tc.batch_size,
            epochs=epochs,
            shuffle=True,
            validation_split=0.02,
        )
        return (state_ary.shape[0] // tc.batch_size) * epochs

    def _compile_model(self):
        from keras.optimizers import Adam
        tc = self.config.trainer
        opt = Adam(learning_rate=tc.learning_rate)
        self.model.model.compile(
            optimizer=opt,
            loss=['categorical_crossentropy', 'mean_squared_error'],
            loss_weights=tc.loss_weights,
        )

    # ── Data loading ──────────────────────────────────────────────────────────

    def _fill_queue(self, data_files: deque):
        """Load data files into self.dataset until dataset_size is reached."""
        futures = deque()
        with ProcessPoolExecutor(
                max_workers=self.config.trainer.cleaning_processes) as executor:
            for _ in range(self.config.trainer.cleaning_processes):
                if not data_files:
                    break
                fname = data_files.popleft()
                futures.append(executor.submit(_load_data_file, fname))

            while futures and len(self.dataset[0]) < self.config.trainer.dataset_size:
                result = futures.popleft().result()
                if result is None:
                    continue
                states, policies, values = result
                self.dataset[0].extend(states)
                self.dataset[1].extend(policies)
                self.dataset[2].extend(values)

                if data_files:
                    fname = data_files.popleft()
                    futures.append(executor.submit(_load_data_file, fname))

    def _collect_data(self):
        """Convert dequeues to numpy arrays for Keras."""
        states = np.asarray(list(self.dataset[0]), dtype=np.float32)
        policies = np.asarray(list(self.dataset[1]), dtype=np.float32)
        values = np.asarray(list(self.dataset[2]), dtype=np.float32)
        # Model expects input shape (batch, 1, STATE_DIM); add the middle dim.
        if states.ndim == 2:
            states = states[:, np.newaxis, :]
        elif states.ndim != 3:
            raise ValueError(
                f"Unexpected states array shape {states.shape}; "
                "expected 2-D (N, STATE_DIM) from the data pipeline."
            )
        return states, policies, values

    # ── Model I/O ─────────────────────────────────────────────────────────────

    def _load_model(self) -> KaryotypeModel:
        model = KaryotypeModel(self.config)
        rc = self.config.resource
        dirs = self._get_next_gen_dirs(rc)
        if not dirs:
            logger.info("No next-gen model found; loading best model.")
            if not model.load(rc.karyotype_model_config_path,
                              rc.karyotype_model_weight_path):
                raise RuntimeError(
                    "No karyotype model found. Run karyotype_self_play first "
                    "to generate an initial model.")
        else:
            latest = dirs[-1]
            model.load(
                os.path.join(latest, rc.next_generation_model_config_filename),
                os.path.join(latest, rc.next_generation_model_weight_filename),
            )
        return model

    def _save_next_generation_model(self):
        rc = self.config.resource
        model_id = datetime.now().strftime("%Y%m%d-%H%M%S.%f")
        model_dir = os.path.join(
            rc.karyotype_next_gen_dir,
            rc.next_generation_model_dirname_tmpl % model_id,
        )
        os.makedirs(model_dir, exist_ok=True)
        config_path = os.path.join(
            model_dir, rc.next_generation_model_config_filename)
        weight_path = os.path.join(
            model_dir, rc.next_generation_model_weight_filename)
        self.model.save(config_path, weight_path)
        logger.info(f"Saved next-gen model to {model_dir}")

    # ── Filesystem helpers ────────────────────────────────────────────────────

    @staticmethod
    def _get_data_filenames(rc) -> list:
        pattern = os.path.join(rc.karyotype_play_data_dir,
                               rc.karyotype_play_data_filename_tmpl % '*')
        return sorted(glob(pattern))

    @staticmethod
    def _get_next_gen_dirs(rc) -> list:
        pattern = os.path.join(rc.karyotype_next_gen_dir,
                               rc.next_generation_model_dirname_tmpl % '*')
        return sorted(glob(pattern))


# ── Subprocess helper ─────────────────────────────────────────────────────────

def _load_data_file(path: str):
    """
    Load one self-play data file.

    Returns
    -------
    (np.ndarray, np.ndarray, np.ndarray) or None
        states  shape (N, N_CHROMOSOMES, input_dim)
        policies shape (N, N_ACTIONS)
        values   shape (N,)
    """
    try:
        import json
        with open(path, 'rt') as f:
            raw = json.load(f)
        states = np.asarray([s for s, p, r in raw], dtype=np.float32)
        policies = np.asarray([p for s, p, r in raw], dtype=np.float32)
        values = np.asarray([r for s, p, r in raw], dtype=np.float32)
        return states, policies, values
    except Exception as exc:
        logger.warning(f"Could not load {path}: {exc}")
        return None
